version: '2.2'
services:
  php:
    container_name: daemon_original
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    links: 
     - mariadb:mariadb
    restart: always
    environment:
     - DB_HOST=mariadb
    depends_on:
     - mariadb
    ports:
     - "1337:80"
    volumes:
     - /opt/chongxun/:/opt/chongxun/
    networks:
      vpcbr:
        ipv4_address: 10.37.13.39
    extra_hosts:
     - "chongxun.gitlab.internal:10.37.13.37"

  mariadb:
    container_name: mariadb_daemon_original
    image: mariadb:latest
    volumes:
     - ./db_data:/var/lib/mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=###CENSORED###
    volumes:
     - ./sql_dump/:/docker-entrypoint-initdb.d
    command: --sql_mode=""
    networks:
      vpcbr:
        ipv4_address: 10.37.13.38

  web:
    build:
      context: .
      dockerfile: ./containers/gitlab/Dockerfile
    container_name: 'gitlab-13.10.2-ee.0-internal'
    restart: always
    hostname: '10.37.13.37'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.37.13.37'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "###CENSORED###@gmail.com"
        gitlab_rails['smtp_password'] = "###CENSORED###"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['initial_root_password'] = "###CENSORED###";

    networks:
      vpcbr:
        ipv4_address: 10.37.13.37


    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

networks:
  vpcbr:
    external: true
    name: chongxun-network
